export interface TrackStatusType {
  ActualDeliveryDate: string
  AdditionalInformationEW: string
  AdjustedDate: string
  AfterpaymentOnGoodsCost: string
  AmountPaid: string
  AmountToPay: string
  AnnouncedPrice: string
  AviaDelivery: number
  BarcodeRedBox: string
  CalculatedWeight: string
  CardMaskedNumber: string
  CargoDescriptionString: string
  CargoReturnRefusal: boolean
  CargoType: string
  CategoryOfWarehouse: string
  CheckWeight: number
  CheckWeightMethod: string
  CityRecipient: string
  CitySender: string
  ClientBarcode: string
  CounterpartyRecipientDescription: string
  CounterpartySenderDescription: string
  CounterpartySenderType: string
  CounterpartyType: string
  CreatedOnTheBasis: string
  DateCreated: string
  DateFirstDayStorage: string
  DateMoving: string
  DatePayedKeeping: string
  DateScan: string
  DaysStorageCargo: string
  DeliveryTimeframe: string
  DocumentCost: string
  DocumentWeight: number
  ExpressWaybillAmountToPay: string
  ExpressWaybillPaymentStatus: string
  FactualWeight: string
  FreeShipping: string
  InternationalDeliveryType: string
  InternetDocumentDescription: string
  LastAmountReceivedCommissionGM: number
  LastAmountTransferGM: string
  LastCreatedOnTheBasisDateTime: string
  LastCreatedOnTheBasisDocumentType: string
  LastCreatedOnTheBasisNumber: string
  LastCreatedOnTheBasisPayerType: string
  LastTransactionDateTimeGM: string
  LastTransactionStatusGM: string
  LoyaltyCardRecipient: string
  LoyaltyCardSender: string
  MarketplacePartnerToken: string
  Number: string
  OwnerDocumentNumber: string
  OwnerDocumentType: string
  Packaging: any[]
  PartialReturnGoods: any[]
  PayerType: string
  PaymentMethod: string
  PaymentStatus: string
  PaymentStatusDate: string
  PhoneRecipient: string
  PhoneSender: string
  PossibilityChangeCash2Card: boolean
  PossibilityChangeDeliveryIntervals: boolean
  PossibilityChangeEW: boolean
  PossibilityCreateRedirecting: boolean
  PossibilityCreateRefusal: boolean
  PossibilityCreateReturn: boolean
  PossibilityTrusteeRecipient: boolean
  PostomatV3CellReservationNumber: boolean
  RecipientAddress: string
  RecipientDateTime: string
  RecipientFullName: string
  RecipientFullNameEW: string
  RecipientWarehouseTypeRef: string
  Redelivery: number
  RedeliveryNum: string
  RedeliveryPayer: string
  RedeliveryPaymentCardDescription: string
  RedeliveryPaymentCardRef: string
  RedeliveryServiceCost: string
  RedeliverySum: string
  RefCityRecipient: string
  RefCitySender: string
  RefEW: string
  RefSettlementRecipient: string
  RefSettlementSender: string
  ScheduledDeliveryDate: string
  SeatsAmount: string
  SecurePayment: boolean
  SenderAddress: string
  SenderFullNameEW: string
  ServiceType: string
  Status: string
  StatusCode: string
  StorageAmount: string
  StoragePrice: string
  SumBeforeCheckWeight: number
  TrackingUpdateDate: string
  TrusteeRecipientPhone: string
  UndeliveryReasons: string
  UndeliveryReasonsDate: string
  UndeliveryReasonsSubtypeDescription: string
  VolumeWeight: string
  WarehouseRecipient: string
  WarehouseRecipientAddress: string
  WarehouseRecipientInternetAddressRef: string
  WarehouseRecipientNumber: number
  WarehouseRecipientRef: string
  WarehouseSender: string
  WarehouseSenderAddress: string
  WarehouseSenderInternetAddressRef: string
}
